// This file is auto-generated by generate-gallery-config.js
window.galleryConfig = {
    "landing": [
        "work/landing/landing_001.JPG",
        "work/landing/landing_002.JPG",
        "work/landing/landing_003.JPG",
        "work/landing/landing_004.JPG"
    ],
    "portfolio-one-of-many": [
        "work/portfolio - one of many/20220909_portfolio_oomredux_wesleyverhoeve for ig 336a4642.JPG",
        "work/portfolio - one of many/20220909_portfolio_oomredux_wesleyverhoevedavidamsden_336a9758.JPG",
        "work/portfolio - one of many/20220909_portfolio_oomredux_wesleyverhoevedraplin_336a6846.JPG",
        "work/portfolio - one of many/20220909_portfolio_oomredux_wesleyverhoeveerin connelly_336a1211.JPG"
    ],
    "portfolio-the-best-medicine": [
        "work/portfolio - the best medicine/20220909_portfolio_oomredux_wesleyverhoevebecca_336a1307.JPG",
        "work/portfolio - the best medicine/20220909_portfolio_oomredux_wesleyverhoevebenclemmons_336a1917.JPG",
        "work/portfolio - the best medicine/20220909_portfolio_oomredux_wesleyverhoevebergerfohr re-edit.JPG",
        "work/portfolio - the best medicine/20220909_portfolio_oomredux_wesleyverhoevebrooks 336a1186.JPG"
    ],
    "portraits-i": [
        "work/portraits I/image_001.jpg",
        "work/portraits I/image_002.jpg",
        "work/portraits I/image_003.jpg",
        "work/portraits I/image_004.jpg",
        "work/portraits I/image_005.jpg",
        "work/portraits I/image_006.jpg",
        "work/portraits I/image_009.jpg"
    ],
    "portraits-ii": [
        "work/portraits II/image_001.jpg",
        "work/portraits II/image_002.jpg",
        "work/portraits II/image_008.jpg",
        "work/portraits II/image_009.jpg"
    ],
    "travel": [
        "work/travel/20220909_portfolio_travel_wesleyverhoeve_2016-03-04-11.29.53.jpg",
        "work/travel/20220909_portfolio_travel_wesleyverhoeve_336A6059.jpg",
        "work/travel/20220909_portfolio_travel_wesleyverhoeve_Honda-2-336A5954.jpg"
    ]
};
